print("This is a program to impliment string")
wordinput = input("Enter a string : ")
joinsymbol = input("join the string with : ")
print ("Does the string entered contain only alphabets ? ", wordinput.isalpha())
print ("Is the string entered contain only lowercase ? ", wordinput.islower())
print ("The upper case of the string entered :", wordinput.upper())
print ("The lower case of the entered string : ", wordinput.lower())
print ("Wether the string entered is in upper case ? : ", wordinput.isupper())
print ("Wether the string is title case ? :", wordinput.title())
print ("Sting after removing space from the left side :  ",wordinput.lstrip())
print ("Sting after removing space from the right side :  ",wordinput.rstrip())
print ("After joining : ",joinsymbol.join(wordinput))
input()
