n1 = float(input("Enter the first number :"))
n2 = float(input("Enter the second number :"))
print(f"The sum of the two numbers is {n1 + n2}")
print(f"The difference between the two numbers is {n1 - n2}")
print(f"The product of the two numbers is {n1 * n2}")
print(f"The division of the two numbers is {n1 / n2}")
input()